# coding: utf-8
# Generated by bundler

lib = File.expand_path('../ext/lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'date'

begin
  gemfiles = []
  Dir::glob("**/**").each do |file_name|
    next if File::directory?(file_name)
    gemfiles << file_name
  end
  raise "Invalid registration of file name" if gemfiles.size == 0

  committer_date = Date.parse('Wed Feb 25 14:21:03 2015 +0900')
  git_revision = '912a25c'
  Gem::Specification.new do |spec|

    spec.name          = "pcap"
    spec.version       = "#{committer_date.strftime("%Y%m%d")}.#{git_revision}"
    spec.required_rubygems_version = Gem::Requirement.new(">= 0") if spec.respond_to? :required_rubygems_version=
  
    spec.authors       = ["Masaki Fukushima", "Andrew Hobson", "KDDI R&D Laboratories"]
    spec.date          = committer_date.to_s
    spec.email         = ["fukusima@goto.info.waseda.ac.jp"]
    spec.summary       = "Interface to LBL Packet Capture library (libpcap)"
    spec.description   = "Ruby interface to LBL Packet Capture library. This library also includes classes to access packet header fields."
    spec.homepage      = "http://www.goto.info.waseda.ac.jp/~fukusima/ruby/pcap-e.html"
    spec.license       = "GPL-2.0"

    spec.extensions    = ["ext/extconf.rb"]
    spec.files         = gemfiles
    spec.executables   = spec.files.grep(%r{^bin/}) { |f| File.basename(f) }
    spec.test_files    = spec.files.grep(%r{^(test|spec|features)/})
    spec.require_paths = ["lib"]
    spec.rdoc_options  = ["--charset=UTF-8"]

    spec.add_development_dependency "bundler", "~> 1.5"
    spec.add_development_dependency "rake"
    spec.add_runtime_dependency "rdoc", ">= 4.0.0"
  end
rescue ArgumentError
  puts "Not been arcived. Run : git archive"
rescue StandardError => e
  puts e
end
